name: Convert Office Files to PDF and Delete Originals

on:
  push:
    paths:
      - '**.doc'
      - '**.docx'
      - '**.ppt'
      - '**.pptx'

jobs:
  convert-and-replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LibreOffice
        run: sudo apt-get update && sudo apt-get install -y libreoffice

      - name: Convert and replace files
        run: |
          for file in $(find . -type f \( -iname "*.doc" -o -iname "*.docx" -o -iname "*.ppt" -o -iname "*.pptx" \)); do
            libreoffice --headless --convert-to pdf "$file" --outdir "$(dirname "$file")"
            rm "$file"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Convert Office files to PDF and delete originals [skip ci]" || echo "No changes to commit"
          git push
